name: "ptp-operator: CI tests AWS"
on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  aws-ci:
    uses: ./.github/workflows/_reusable-ptp-operator-aws-ci.yml
    secrets: inherit
